server:
  context-path: /
  port: 8883
  session:
    timeout: 900

spring:
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  profiles:
      active: pro

mybatis:
    type-aliases-package: cn.like.girl.blog
    mapper-locations: classpath:cn/like/girl/blog/mapping/*.xml

logging:
    level:
        tk.mybatis: TRACE


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

